apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-ca-secretstore
  namespace: argocd
spec:
  provider:
    vault:
      server: "http://192.168.0.184:31820"
      path: "pki"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "pipeline1-cluster"
          # A required field containing the Vault Role to assume.
          role: "argocd"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "argocd-dex-server"
