apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.deployments-status: ""
spec:
  project: demo-deployment
  source:
    path: deployments/test
    repoURL: https://github.com/lanbingcloud/demo-user-deployments.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: user-deployments
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
