apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../argocd/overlays/production
patchesStrategicMerge:
- argocd-cm-patch.yaml
- argocd-rbac-cm-patch.yaml
namespace: argocd
