apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repository-pvc
  namespace: user-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
