---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline:deployments-listener
  namespace: user-pipelines
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline:deployments-listener
  namespace: user-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline:deployments-listener
subjects:
- kind: ServiceAccount
  name: default
  namespace: user-pipelines
