apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster2-patch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-vcluster
  source:
    path: vclusters/vcluster2/vcluster2-patch
    repoURL: https://github.com/lanbingcloud/demo-sso-dex.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
