apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idp-ca-secret
  namespace: vcluster1
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vcluster1-ca-secretstore
    kind: SecretStore
  target:
    name: idp-ca-secret
  data:
  - secretKey: ca.crt
    remoteRef:
      key: default
      property: ca.crt
