apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idp-ca-secret
  namespace: oauth2-proxy
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: oauth2-proxy-ca-secretstore
    kind: SecretStore
  target:
    name: idp-ca-secret
  data:
  - secretKey: ca.crt
    remoteRef:
      key: default
      property: ca.crt
