apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idp-ca-secret
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: argocd-ca-secretstore
    kind: SecretStore
  target:
    name: idp-ca-secret
  data:
  - secretKey: ca-certs-Private-DEX.pem
    remoteRef:
      key: default
      property: ca.crt
