apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cm
data:
  url: "https://argocd.119-8-58-20.nip.io:30443"
  dex.config: |
    connectors:
      - type: oidc
        id: dex
        name: Dex
        config:
          issuer: https://dex.119-8-58-20.nip.io:31443
          clientID: demo
          clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
          insecureEnableGroups: true
          scopes:
          - "openid"
          - "profile"
          - "email"
          - "groups"
          getUserInfo: true
