apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- argocd-cm-patch.yaml
- argocd-dex-server-patch.yaml
- argocd-server-svc-patch.yaml
- argocd-notifications-cm-patch.yaml
