apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secret
  namespace: dex
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: dex-secretstore
    kind: SecretStore
  target:
    name: dex-secret
  data:
  - secretKey: github-client-id
    remoteRef:
      key: github/client
      property: id
  - secretKey: github-client-secret
    remoteRef:
      key: github/client
      property: secret
