apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- secretstore.yaml
- external-dex-secret.yaml
- external-dex.example.com.tls.yaml
- ingress-dex.yaml
patchesStrategicMerge:
- dex-cm-patch.yaml
- dex-deployment-patch.yaml
