apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dex-secretstore
  namespace: dex
spec:
  provider:
    vault:
      server: "http://192.168.0.184:31820"
      path: "dex"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "host-cluster"
          # A required field containing the Vault Role to assume.
          role: "dex"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "dex"
