apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  github:
    user-project:
      repositories:
        - owner: lanbingcloud
          names:
            - demo-user-project
      webhook:
        endpoint: /user-project
        port: "12000"
        method: POST
        url: http://webhook.pipeline1.119-8-58-20.nip.io:30080
      events:
        - "push"
      apiToken:
        key: token
        name: github-access
      wehookSecret:
        key: secret
        name: github-access
      insecure: true
      active: true
      contentType: json
